# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
services:
  searchqna:
    build:
      dockerfile: SearchQnA/docker/Dockerfile
    image: ${REGISTRY}opea/searchqna:${TAG:-latest}
  searchqna-ui:
    build:
      dockerfile: SearchQnA/docker/ui/docker/Dockerfile
    image: ${REGISTRY}opea/searchqna-ui:${TAG:-latest}
