# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
services:
  translation:
    build:
      dockerfile: Translation/docker/Dockerfile
    image: ${REGISTRY}opea/translation:${TAG:-latest}
  translation-ui:
    build:
      dockerfile: Translation/docker/ui/docker/Dockerfile
    image: ${REGISTRY}opea/translation-ui:${TAG:-latest}
